function testRebaseWithError() {
    console.log('Error1');
    console.log('Error2');
}